const char_star = [
    {
        id : 0,
        name : 'Voyager',
        motiv : 'star',
        src : './public/char_img/star/voyager.png',
        prtSrc : './public/char_portrait/voyager.webp',
        bg : './public/char_bg/voyager_bg.webp',
        psyName1: '오락 지상주의',
        psyName2: '멋진 신세계',
        psySrc1: './public/psychube/오락.png',
        psySrc2: './public/psychube/신세계.png',
        emo: './public/char_emo/voyager_emo.png',
        res1: './public/resonance/voyager_7_att.png',
        res2: './public/resonance/voyager_9_att.png',
        res3: './public/resonance/voyager_10_att.png',
        resName1: '7공명(공격)',
        resName2: '9공명(공격)',
        resName3: '10공명 이상(공격)',
        resPattern: './public/resonance_pattern/밸런스형_이해.png',
        resPatternName: '이해',
        resPatternText: '최종 술식 위력/피해',
        party_1_1: './public/char_img/star/barcarola.png',
        party_1_2: './public/char_img/star/voyager.png',
        party_1_3: './public/char_img/star/flutterpage.png',
        party_1_4: './public/char_img/star/tooth_fairy.png',
        party_2_1: './public/char_img/star/voyager.png',
        party_2_2: './public/char_img/star/regulus.png',
        party_2_3: './public/char_img/star/tooth_fairy.png',
        party_2_4: './public/plus.png'
    },

    {
        id : 1,
        name : 'Lilya',
        motiv : 'star',
        src : './public/char_img/star/lilya.png',
        prtSrc : './public/char_portrait/lilya.webp',
        bg : './public/char_bg/lilya_bg.webp',
        psyName1: '성 밖의 세상',
        psyName2: '증명 시도',
        psySrc1: './public/psychube/성_밖의_세상.png',
        psySrc2: './public/psychube/증명_시도.png',
        emo: './public/char_emo/lilya_emo.png',
        res1: './public/resonance/lilya_7_crit.png',
        res2: './public/resonance/lilya_9_crit.png',
        res3: './public/resonance/lilya_10_crit.png',
        resName1: '7공명(치명)',
        resName2: '9공명(치명)',
        resName3: '10공명 이상(치명)',
        resPattern: './public/resonance_pattern/공격형_이해.png',
        resPatternName: '이해',
        resPatternText: '치명타 피해/공격',
        party_1_1: './public/char_img/star/lilya.png',
        party_1_2: './public/char_img/star/37.png',
        party_1_3: './public/char_img/beast/lopera.png',
        party_1_4: './public/char_img/mineral/newbabel.png',
        party_2_1: './public/char_img/star/lilya.png',
        party_2_2: './public/char_img/intellect/lucy.png',
        party_2_3: './public/char_img/star/flutterpage.png',
        party_2_4: './public/char_img/beast/lopera.png'
    },

    {
        id : 2,
        name : 'Regulus',
        motiv : 'star',
        src : './public/char_img/star/regulus.png',
        prtSrc : './public/char_portrait/regulus.webp',
        bg : './public/char_bg/regulus_bg.png',
        psyName1: '용감한 전진',
        psyName2: '멋진 신세계(1형상+)',
        psySrc1: './public/psychube/용감한_전진.png',
        psySrc2: './public/psychube/신세계.png',
        emo: './public/char_emo/regulus_emo.png',
        res1: './public/resonance/regulus_7_att.png',
        res2: './public/resonance/regulus_9_crit.png',
        res3: './public/resonance/regulus_10_atcr.png',
        resName1: '7공명(공격)',
        resName2: '9공명(치명)',
        resName3: '10공명 이상(공&치)',
        resPattern: './public/resonance_pattern/보조형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/star/regulus.png',
        party_1_2: './public/char_img/star/37.png',
        party_1_3: './public/char_img/star/lilya.png',
        party_1_4: './public/char_img/star/tooth_fairy.png',
    },

    {
        id : 3,
        name : 'Tooth_Fairy',
        motiv : 'star',
        src : './public/char_img/star/tooth_fairy.png',
        prtSrc : './public/char_portrait/tooth_fairy.webp',
        bg : './public/char_bg/tooth_fairy_bg.webp',
        psyName1: '호기심쟁이(힐량)',
        psyName2: '원더랜드 바깥(레이드)',
        psySrc1: './public/psychube/호기심쟁이.png',
        psySrc2: './public/psychube/원더랜드_바깥.png',
        emo: './public/char_emo/tf_emo.png',
        res1: './public/resonance/tf_7_crit.png',
        res2: './public/resonance/tf_9_crit.png',
        res3: './public/resonance/tf_10_crit.png',
        resName1: '7공명(치명)',
        resName2: '9공명(치명)',
        resName3: '10공명 이상(치명)',
        resPattern: './public/resonance_pattern/공격형_불시의_의아함.png',
        resPatternName: '불시의 의아함',
        resPatternText: '치명타율/공격',
    },

    {
        id : 4,
        name : '37',
        motiv : 'star',
        src : './public/char_img/star/37.png',
        prtSrc : './public/char_portrait/37.webp',
        bg : './public/char_bg/37_bg.webp',
        psyName1: '현상에 남다',
        psyName2: '기나긴 속삭임',
        psySrc1: './public/psychube/현상에_남다.png',
        psySrc2: './public/psychube/기나긴_속삭임.png',
        emo: './public/char_emo/37_emo.png',
        res1: './public/resonance/37_7_att.png',
        res2: './public/resonance/37_9_att.png',
        res3: './public/resonance/37_10_att.png',
        resName1: '7공명(공격)',
        resName2: '9공명(공격)',
        resName3: '10공명 이상(공격)',
        resPattern: './public/resonance_pattern/공격형_희망.png',
        resPatternName: '희망',
        resPatternText: '치명타 피해/공격',
    },

    {
        id : 5,
        name : 'Ezra',
        motiv : 'star',
        src : './public/char_img/star/ezra.png',
        prtSrc : './public/char_portrait/ezra.webp',
        bg : './public/char_bg/ezra_bg.webp',
        psyName1: '원더랜드 바깥',
        psyName2: '두 번째 생명',
        psySrc1: './public/psychube/원더랜드_바깥.png',
        psySrc2: './public/psychube/두_번째_생명.png',
        emo: './public/char_emo/ezra_emo.png',
        res1: './public/resonance/ezra_7_hp.png',
        res2: './public/resonance/ezra_9_hp.png',
        res3: './public/resonance/ezra_10_hp.png',
        resName1: '7공명(생존)',
        resName2: '9공명(생존)',
        resName3: '10공명 이상(생존)',
        resPattern: './public/resonance_pattern/공격형_불시의_의아함.png',
        resPatternName: '불시의 의아함',
        resPatternText: '치명타율/공격',
    },

    {
        id : 6,
        name : 'Windsong',
        motiv : 'star',
        src : './public/char_img/star/windsong.png',
        prtSrc : './public/char_portrait/windsong.webp',
        bg : './public/char_bg/windsong_bg.webp',
        psyName1: '또 다른 이야기',
        psyName2: '밤의 모독자',
        psySrc1: './public/psychube/또_다른_이야기.png',
        psySrc2: './public/psychube/밤의_모독자.png',
        emo: './public/char_emo/windsong_emo.png',
        res1: './public/resonance/windsong_7_atcr.png',
        res2: './public/resonance/windsong_10_atcr.png',
        res3: './public/resonance/windsong_12_atcr.png',
        resName1: '7공명(공&치)',
        resName2: '10공명(공&치)',
        resName3: '12공명 이상(공&치)',
        resPattern: './public/resonance_pattern/밸런스형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
    },

    {
        id : 7,
        name : 'Flutterpage',
        motiv : 'star',
        src : './public/char_img/star/flutterpage.png',
        prtSrc : './public/char_portrait/flutterpage.webp',
        bg : './public/char_bg/flutterpage_bg.webp',
        psyName1: '초침의 서식지',
        psyName2: '미로의 밖',
        psySrc1: './public/psychube/초침의_서식지.png',
        psySrc2: './public/psychube/미로의_밖.png',
        emo: './public/char_emo/fp_emo.png',
        res1: './public/resonance/fp_7_atcr.png',
        res2: './public/resonance/fp_10_atcr.png',
        res3: './public/resonance/fp_15_atcr.png',
        resName1: '7공명(공&치)',
        resName2: '10공명(공&치)',
        resName3: '15공명(공&치)',
        resPattern: './public/resonance_pattern/공격형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
    },

    {
        id : 8,
        name: "Barcarola",
        motiv: "star",
        src: "./public/char_img/star/barcarola.png",
        prtSrc : './public/char_portrait/barcarola.webp',
        bg : './public/char_bg/barcarola_bg.webp',
        psyName1: '이별 변주곡',
        psyName2: '밤의 깊은 곳',
        psySrc1: './public/psychube/이별_변주곡.png',
        psySrc2: './public/psychube/밤의_깊은_곳.png',
        emo: './public/char_emo/barcarola_emo.png',
        res1: './public/resonance/bar_7_atcr.png',
        res2: './public/resonance/bar_10_atcr.png',
        res3: './public/resonance/bar_15_atcr.png',
        resName1: '7공명(공&치)',
        resName2: '10공명(공&치)',
        resName3: '15공명(공&치)',
        resPattern: './public/resonance_pattern/보조형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/star/barcarola.png',
        party_1_2: './public/char_img/star/voyager.png',
        party_1_3: './public/char_img/star/flutterpage.png',
        party_1_4: './public/char_img/mineral/patutu.png',
        party_2_1: './public/char_img/star/barcarola.png',
        party_2_2: './public/char_img/star/voyager.png',
        party_2_3: './public/char_img/intellect/aleph.png',
        party_2_4: './public/char_img/star/kiperina.png'
    },

    {
        id : 9,
        name: "LiangYue",
        motiv: "star",
        src: "./public/char_img/star/liangyue.png",
        prtSrc : './public/char_portrait/liangyue.webp',
        bg : './public/char_bg/liangyue_bg.webp',
        psyName1: '응답 대기',
        psyName2: '밤의 깊은 곳',
        psySrc1: './public/psychube/응답_대기.png',
        psySrc2: './public/psychube/밤의_깊은_곳.png',
        emo: './public/char_emo/liang_emo.png',
        res1: './public/resonance/liang_7_atcr.png',
        res2: './public/resonance/liang_10_atcr.png',
        res3: './public/resonance/liang_15_atcr.png',
        resName1: '7공명(공&치)',
        resName2: '10공명(공&치)',
        resName3: '15공명(공&치)',
        resPattern: './public/resonance_pattern/공격형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/star/liangyue.png',
        party_1_2: './public/char_img/star/37.png',
        party_1_3: './public/char_img/star/flutterpage.png',
        party_1_4: './public/char_img/mineral/patutu.png',
        party_2_1: './public/char_img/star/liangyue.png',
        party_2_2: './public/char_img/beast/anjoNala.png',
        party_2_3: './public/char_img/star/flutterpage.png',
        party_2_4: './public/char_img/mineral/patutu.png'
    },

    {
        id : 10,
        name: "Kiperina",
        motiv: "star",
        src: "./public/char_img/star/kiperina.png",
    }
]

const char_mineral = [
    {
        id : 0,
        name : 'NewBabel',
        motiv : 'mineral',
        src : './public/char_img/mineral/newbabel.png',
        prtSrc : './public/char_portrait/newbabel.webp',
        bg : './public/char_bg/newbabel_bg.webp',
        psyName1: '가까워지는 빗소리(생존)',
        psyName2: '성 밖의 세상(공격)',
        psySrc1: './public/psychube/가까워지는_빗소리.png',
        psySrc2: './public/psychube/성_밖의_세상.png',
        emo: './public/char_emo/newbabel_emo.png',
        res1: './public/resonance/newbabel_7_hp.png',
        res2: './public/resonance/newbabel_9_hp.png',
        res3: './public/resonance/newbabel_10_hp.png',
        resName1: '7공명(생존)',
        resName2: '9공명(생존)',
        resName3: '10공명 이상(생존)',
        resPattern: './public/resonance_pattern/방어형_고요.png',
        resPatternName: '고요',
        resPatternText: '현실 방어',
        party_1_1: './public/char_img/mineral/newbabel.png',
        party_1_2: './public/char_img/beast/J.png',
        party_1_3: './public/char_img/star/flutterpage.png',
        party_1_4: './public/char_img/beast/lopera.png',
        party_2_1: './public/char_img/mineral/newbabel.png',
        party_2_2: './public/plus.png'
    },

    {
        id : 1,
        name : 'Eternity',
        motiv : 'mineral',
        src : './public/char_img/mineral/eternity.png',
        prtSrc : './public/char_portrait/eternity.webp',
        bg : './public/char_bg/eternity_bg.webp',
        psyName1: '가장 깊은 곳에서(생존)',
        psyName2: '밤이면 밤마다(공격)',
        psySrc1: './public/psychube/가장_깊은_곳에서.png',
        psySrc2: './public/psychube/밤이면_밤마다.png',
        emo: './public/char_emo/eternity_emo.png',
        res1: './public/resonance/eternity_7_bl.png',
        res2: './public/resonance/eternity_10_bl.png',
        res3: './public/resonance/eternity_15_bl.png',
        resName1: '7공명(균형)',
        resName2: '9공명(균형)',
        resName3: '10공명 이상(균형)',
        resPattern: './public/resonance_pattern/밸런스형_순환균형.png',
        resPatternName: '순환 균형',
        resPatternText: '종합',
        party_1_1: './public/char_img/mineral/semmelweiss.png',
        party_1_2: './public/char_img/mineral/pickles.png',
        party_1_3: './public/char_img/mineral/eternity.png',
        party_1_4: './public/char_img/beast/medicinePocket.png',
    },

    {
        id : 2,
        name : 'Pickles',
        motiv : 'mineral',
        src : './public/char_img/mineral/pickles.png',
        prtSrc : './public/char_portrait/pickles.webp',
        bg : './public/char_bg/pickles_bg.webp',
        psyName1: '좁은 문을 두드려라(단기)',
        psyName2: '오락 지상주의(장기)',
        psySrc1: './public/psychube/좁은_문을_두드려라.png',
        psySrc2: './public/psychube/오락.png',
        emo: './public/char_emo/pickles_emo.png',
        res1: './public/resonance/balance_7_attack.png',
        res2: './public/resonance/balance_9_attack.png',
        res3: './public/resonance/pickles_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/밸런스형_이해.png',
        resPatternName: '이해',
        resPatternText: '술식 위력/피해',
        party_1_1: './public/char_img/mineral/semmelweiss.png',
        party_1_2: './public/char_img/mineral/pickles.png',
        party_1_3: './public/char_img/mineral/eternity.png',
        party_1_4: './public/char_img/beast/medicinePocket.png',
        party_2_1: './public/char_img/mineral/jiuniangzi.png',
        party_2_2: './public/char_img/mineral/pickles.png',
        party_2_3: './public/char_img/mineral/patutu.png',
        party_2_4: './public/char_img/beast/lopera.png',
    },

    {
        id : 3,
        name : 'KaalaBauna',
        motiv : 'mineral',
        src : './public/char_img/mineral/kaalabauna.png',
        prtSrc : './public/char_portrait/kaala_bauna.webp',
        bg : './public/char_bg/kaala_bauna_bg.webp',
        psyName1: '오락 지상주의',
        psyName2: '멋진 신세계',
        psySrc1: './public/psychube/오락.png',
        psySrc2: './public/psychube/신세계.png',
        emo: './public/char_emo/kaala_bauna_emo.png',
        res1: './public/resonance/balance_7_attack.png',
        res2: './public/resonance/balance_9_attack.png',
        res3: './public/resonance/kaala_bauna_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/밸런스형_이해.png',
        resPatternName: '이해',
        resPatternText: '술식 위력/피해',
    
    },

    {
        id : 4,
        name : 'JiuNiangzi',
        motiv : 'mineral',
        src : './public/char_img/mineral/jiuniangzi.png',
        prtSrc : './public/char_portrait/ziu_niangzi.webp',
        bg : './public/char_bg/ziu_niangzi_bg.webp',
        psyName1: '성 밖의 세상',
        psyName2: '초침의 서식지',
        psySrc1: './public/psychube/성_밖의_세상.png',
        psySrc2: './public/psychube/초침의_서식지.png',
        emo: './public/char_emo/ziu_niangzi_emo.png',
        res1: './public/resonance/balance_7_attack.png',
        res2: './public/resonance/balance_9_attack.png',
        res3: './public/resonance/ziu_niangzi_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/밸런스형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/mineral/jiuniangzi.png',
        party_1_2: './public/char_img/mineral/pickles.png',
        party_1_3: './public/char_img/mineral/patutu.png',
        party_1_4: './public/char_img/beast/lopera.png',
    },

    {
        id : 5,
        name : 'Semmelweiss',
        motiv : 'mineral',
        src : './public/char_img/mineral/semmelweiss.png',
        prtSrc : './public/char_portrait/semmelweiss.webp',
        bg : './public/char_bg/semmelweiss_bg.webp',
        psyName1: '응답 대기',
        psyName2: '가장 깊은 곳에서',
        psySrc1: './public/psychube/응답_대기.png',
        psySrc2: './public/psychube/가장_깊은_곳에서.png',
        emo: './public/char_emo/semmelweiss_emo.png',
        res1: './public/resonance/balance_7_attack.png',
        res2: './public/resonance/balance_9_attack.png',
        res3: './public/resonance/semmelweiss_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/밸런스형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/mineral/semmelweiss.png',
        party_1_2: './public/char_img/mineral/pickles.png',
        party_1_3: './public/char_img/mineral/eternity.png',
        party_1_4: './public/char_img/beast/medicinePocket.png',
    },

    {
        id : 6,
        name : 'Patutu',
        motiv : 'mineral',
        src : './public/char_img/mineral/patutu.png',
        prtSrc : './public/char_portrait/patutu.webp',
        bg : './public/char_bg/patutu_bg.webp',
        psyName1: '조개껍데기(보조)',
        psyName2: '성 밖의 세상(공격)',
        psySrc1: './public/psychube/조개껍데기.png',
        psySrc2: './public/psychube/성_밖의_세상.png',
        emo: './public/char_emo/patutu_emo.png',
        res1: './public/resonance/support_7.png',
        res2: './public/resonance/support_9_attack.png',
        res3: './public/resonance/patutu_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/보조형_광분.png',
        resPatternName: '광분',
        resPatternText: '공격',
        party_1_1: './public/char_img/star/liangyue.png',
        party_1_2: './public/char_img/star/37.png',
        party_1_3: './public/char_img/star/flutterpage.png',
        party_1_4: './public/char_img/mineral/patutu.png',
        party_2_1: './public/char_img/mineral/patutu.png',
        party_2_2: './public/plus.png'
    },

    {
        id : 7,
        name : 'Recoleta',
        motiv : 'mineral',
        src : './public/char_img/mineral/recoleta.png'
    }
]

const char_plant = [
    {
        id : 0,
        name : 'DruvisIII',
        motiv : 'plant',
        src : './public/char_img/plant/druvis.png',
        prtSrc : './public/char_portrait/druvis.webp',
        bg : './public/char_bg/druvis_bg.webp',
        psyName1: '땅따먹기 게임',
        psyName2: '마음의 방향',
        psySrc1: './public/psychube/땅따먹기_게임.png',
        psySrc2: './public/psychube/마음의_방향.png',
        emo: './public/char_emo/druvis_emo.png',
        res1: './public/resonance/balance_7_attack.png',
        res2: './public/resonance/balance_9_attack.png',
        res3: './public/resonance/druvis_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/밸런스형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/plant/hisabeth.png',
        party_1_2: './public/char_img/plant/druvis.png',
        party_1_3: './public/char_img/plant/kakania.png',
        party_1_4: './public/char_img/plant/vila.png',
        party_2_1: './public/char_img/plant/jessica.png',
        party_2_2: './public/char_img/plant/druvis.png',
        party_2_3: './public/char_img/plant/ananli.png',
        party_2_4: './public/char_img/plant/sotheby.png',

    },

    {
        id : 1,
        name : 'AnanLi',
        motiv : 'plant',
        src : './public/char_img/plant/ananli.png',
        prtSrc : './public/char_portrait/ananli.webp',
        bg : './public/char_bg/ananli_bg.webp',
        psyName1: '기나긴 속삭임',
        psyName2: '친절한 퇴마사(나무)',
        psySrc1: './public/psychube/기나긴_속삭임.png',
        psySrc2: './public/psychube/친절한_퇴마사.png',
        emo: './public/char_emo/ananli_emo.png',
        res1: './public/resonance/support_7.png',
        res2: './public/resonance/support_9_attack.png',
        res3: './public/resonance/ananli_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/보조형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        party_1_1: './public/char_img/plant/jessica.png',
        party_1_2: './public/char_img/plant/druvis.png',
        party_1_3: './public/char_img/plant/ananli.png',
        party_1_4: './public/char_img/plant/sotheby.png',
        party_2_1: './public/char_img/plant/noire.png',
        party_2_2: './public/char_img/beast/melania.png',
        party_2_3: './public/char_img/plant/ananli.png',
        party_2_4: './public/char_img/beast/lopera.png',
    },

    {
        id : 2,
        name : 'Sotheby',
        motiv : 'plant',
        src : './public/char_img/plant/sotheby.png',
        prtSrc : './public/char_portrait/sotheby.webp',
        bg : './public/char_bg/sotheby_bg.webp',
        psyName1: '무색',
        psyName2: '호기심쟁이',
        psySrc1: './public/psychube/무색.png',
        psySrc2: './public/psychube/호기심쟁이.png',
        emo: './public/char_emo/sotheby_emo.png',
        res1: './public/resonance/balance_7.png',
        res2: './public/resonance/balance_9.png',
        res3: './public/resonance/sotheby_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/밸런스형_순환균형.png',
        resPatternName: '순환 균형',
        resPatternText: '종합',
        party_1_1: './public/char_img/plant/willow.png',
        party_1_2: './public/char_img/spirit/tuesday.png',
        party_1_3: './public/char_img/plant/kakania.png',
        party_1_4: './public/char_img/plant/sotheby.png',
        party_2_1: './public/char_img/plant/jessica.png',
        party_2_2: './public/char_img/plant/druvis.png',
        party_2_3: './public/char_img/plant/ananli.png',
        party_2_4: './public/char_img/plant/sotheby.png',
    },

    {
        id : 3,
        name : 'Jessica',
        motiv : 'plant',
        src : './public/char_img/plant/jessica.png',
        prtSrc : './public/char_portrait/jessica.webp',
        bg : './public/char_bg/jessica_bg.webp',
        psyName1: '밤의 모독자',
        psyName2: '땅따먹기 게임',
        psySrc1: './public/psychube/밤의_모독자.png',
        psySrc2: './public/psychube/땅따먹기_게임.png',
        emo: './public/char_emo/jessica_emo.png',
        res1: './public/resonance/support_7.png',
        res2: './public/resonance/support_9_attack.png',
        res3: './public/resonance/jessica_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/보조형_광분.png',
        resPatternName: '광분',
        resPatternText: '공격',
        party_1_1: './public/char_img/plant/jessica.png',
        party_1_2: './public/char_img/plant/druvis.png',
        party_1_3: './public/char_img/plant/ananli.png',
        party_1_4: './public/char_img/plant/sotheby.png',
        party_2_1: './public/char_img/plant/jessica.png',
        party_2_2: './public/char_img/plant/druvis.png',
        party_2_3: './public/char_img/plant/ananli.png',
        party_2_4: './public/char_img/plant/sotheby.png',
    },

    {
        id : 4,
        name : 'Marcus',
        motiv : 'plant',
        src : './public/char_img/plant/marcus.png',
         prtSrc : './public/char_portrait/marcus.webp',
        bg : './public/char_bg/marcus_bg.webp',
        psyName1: '또 다른 이야기',
        psyName2: '땅따먹기 게임',
        psySrc1: './public/psychube/또_다른_이야기.png',
        psySrc2: './public/psychube/땅따먹기_게임.png',
        emo: './public/char_emo/marcus_emo.png',
        res1: './public/resonance/support_7.png',
        res2: './public/resonance/support_9_attack.png',
        res3: './public/resonance/marcus_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/보조형_정성.png',
        resPatternName: '정성',
        resPatternText: '마법 위력/방어 무시',
        // party_1_1: './public/char_img/plant/willow.png',
        // party_1_2: './public/char_img/spirit/tuesday.png',
        // party_1_3: './public/char_img/plant/kakania.png',
        // party_1_4: './public/char_img/plant/sotheby.png',
        // party_2_1: './public/char_img/plant/jessica.png',
        // party_2_2: './public/char_img/plant/druvis.png',
        // party_2_3: './public/char_img/plant/ananli.png',
        // party_2_4: './public/char_img/plant/sotheby.png',
    },

    {
        id : 5,
        name : 'Vila',
        motiv : 'plant',
        src : './public/char_img/plant/vila.png',
         prtSrc : './public/char_portrait/vila.webp',
        bg : './public/char_bg/vila_bg.webp',
        psyName1: '새벽이 다가온다',
        psyName2: '불완전한 스텝(술식)',
        psySrc1: './public/psychube/새벽이_다가온다.png',
        psySrc2: './public/psychube/불완전한_스텝.png',
        emo: './public/char_emo/vila_emo.png',
        res1: './public/resonance/vila_7.png',
        res2: './public/resonance/vila_9.png',
        res3: './public/resonance/vila_10.png',
        resName1: '7공명',
        resName2: '9공명',
        resName3: '10공명 이상',
        resPattern: './public/resonance_pattern/방어형_광분.png',
        resPatternName: '광분',
        resPatternText: '공격',
        party_1_1: './public/char_img/plant/hisabeth.png',
        party_1_2: './public/char_img/plant/druvis.png',
        party_1_3: './public/char_img/plant/kakania.png',
        party_1_4: './public/char_img/plant/vila.png',
        party_2_1: './public/char_img/plant/jessica.png',
        party_2_2: './public/char_img/plant/druvis.png',
        party_2_3: './public/char_img/plant/ananli.png',
        party_2_4: './public/char_img/plant/sotheby.png',
    },

    {
        id : 6,
        name : 'Kakania',
        motiv : 'plant',
        src : './public/char_img/plant/kakania.png'
    },

    {
        id : 7,
        name : 'Argus',
        motiv : 'plant',
        src : './public/char_img/plant/argus.png'
    },

    {
        id : 8,
        name : 'Willow',
        motiv : 'plant',
        src : './public/char_img/plant/willow.png'
    },

    {
        id : 9,
        name : 'Noire',
        motiv : 'plant',
        src : './public/char_img/plant/noire.png'
    },

    {
        id : 10,
        name : 'Hisabeth',
        motiv : 'plant',
        src : './public/char_img/plant/hisabeth.png'
    }
]

const char_beast = [
    {
        id : 0,
        name : 'Centurion',
        motiv : 'beast',
        src : './public/char_img/beast/centurion.png'
    },

    {
        id : 1,
        name : 'MedicinePocket',
        motiv : 'beast',
        src : './public/char_img/beast/medicinePocket.png'
    },

    {
        id : 2,
        name : 'Melania',
        motiv : 'beast',
        src : './public/char_img/beast/melania.png'
    },

    {
        id : 3,
        name : 'Shamane',
        motiv : 'beast',
        src : './public/char_img/beast/shamane.png'
    },

    {
        id : 4,
        name : 'Spathodea',
        motiv : 'beast',
        src : './public/char_img/beast/spathodea.png'
    },

    {
        id : 5,
        name : 'Getian',
        motiv : 'beast',
        src : './public/char_img/beast/getian.png'
    },

    {
        id : 6,
        name : 'J',
        motiv : 'beast',
        src : './public/char_img/beast/j.png'
    },

    {
        id : 7,
        name : 'AnjoNala',
        motiv : 'beast',
        src : './public/char_img/beast/anjoNala.png'
    },

    {
        id : 8,
        name : 'Lopera',
        motiv : 'beast',
        src : './public/char_img/beast/lopera.png'
    },
]

const char_spirit = [
    {
        id : 0,
        name : 'AKnight',
        motiv : 'spirit',
        src : './public/char_img/spirit/aknight.png'
    },

    {
        id : 1,
        name : 'Isolde',
        motiv : 'spirit',
        src : './public/char_img/spirit/isolde.png'
    },

    {
        id : 2,
        name : 'Mercuria',
        motiv : 'spirit',
        src : './public/char_img/spirit/mercuria.png'
    },

    {
        id : 3,
        name : 'Tuesday',
        motiv : 'spirit',
        src : './public/char_img/spirit/tuesday.png'
    }
]

const char_intellect = [
    {
        id : 0,
        name : '6',
        motiv : 'intellect',
        src : './public/char_img/intellect/6.png' 
    },

    {
        id : 1,
        name : 'Lucy',
        motiv : 'intellect',
        src : './public/char_img/intellect/lucy.png' 
    },

    {
        id : 2,
        name : 'Aleph',
        motiv : 'intellect',
        src : './public/char_img/intellect/aleph.png' 
    }
]

export { char_star, char_mineral, char_plant, char_beast, char_spirit, char_intellect };